apiVersion: batch/v1
kind: Job
metadata:
  name: webhook-cert-setup
spec:
  template:
    spec:
      serviceAccountName: webhook-cert-sa
      containers:
      - name: webhook-cert-setup
        # This is a minimal kubectl image based on Alpine Linux that signs certificates using the k8s extension api server
        image: kansberrycincom/k8s-webhook-cert-manager:0.0.1
        command: ["./generate_certificate.sh"]
        args:
          - "--service"
          - "mutating-webhook-service"
          - "--webhook"
          - "mutating-webhook.cincomcloud.com"
          - "--secret"
          - "mutating-tls-secret"
          - "--namespace"
          - "default"
      restartPolicy: OnFailure
  backoffLimit: 3
